llm_config:
  # Setup chat/reasoning model, for sematic reasoning 
  CHAT_MODEL_API:
    api: sk-6f27c88843124ca5a0bfc4d6b500b011
    url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model: qwen3.5-plus
    type: openai # Only openai api-compatible llm is supported, for now
  # Setup molti-modal chat model(w/ at least vision ability)
  MULTIMODAL_CHAT_MODEL_API:
    api: sk-6f27c88843124ca5a0bfc4d6b500b011
    url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model: qwen3.5-plus
    type: openai # Only openai api-compatible llm is supported, for now
  # Tun on and off thinking/search here for both chat and mmchat model
  ENABLE_THINKING: true
  ENABLE_SEARCH: false


